"""Thematic summary tree and global answering (Phase 5)."""

from .global_qa import GlobalPipeline, extract_summary_citations
from .prompts import (
    MAP_USER_PROMPT,
    PROMPT_VERSION,
    REDUCE_USER_PROMPT,
    SUMMARY_SYSTEM_PROMPT,
    SUMMARY_USER_PROMPT,
    build_map_prompt,
    build_reduce_prompt,
    build_summary_prompt,
    render_summary_documents,
)
from .summarizer import Summarizer, load_summary_cache, summary_cache_key
from .tree import (
    SummaryNode,
    SummaryTree,
    TreeManifest,
    TreeRun,
    build_tree,
    chapter_node_id,
    load_manifest,
    load_tree,
    root_node_id,
    source_hash,
    tree_hash,
    tree_identity,
    window_node_id,
)

__all__ = [
    "MAP_USER_PROMPT",
    "PROMPT_VERSION",
    "REDUCE_USER_PROMPT",
    "SUMMARY_SYSTEM_PROMPT",
    "SUMMARY_USER_PROMPT",
    "GlobalPipeline",
    "Summarizer",
    "SummaryNode",
    "SummaryTree",
    "TreeManifest",
    "TreeRun",
    "build_map_prompt",
    "build_reduce_prompt",
    "build_summary_prompt",
    "build_tree",
    "chapter_node_id",
    "extract_summary_citations",
    "load_manifest",
    "load_summary_cache",
    "load_tree",
    "render_summary_documents",
    "root_node_id",
    "source_hash",
    "summary_cache_key",
    "tree_hash",
    "tree_identity",
    "window_node_id",
]
