"""Serving configuration and emission for a registered GGUF (Phase 4).

The repository never launches a server: registration writes the Ollama
Modelfile and the ``serve.sh`` script with the exact commands for partial GPU
offload on a 4 GB card, and the CLI prints them.
"""

from __future__ import annotations

from pydantic import Field

from ..models import DomainModel
from ..rag.prompts import build_system_prompt

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8080
DEFAULT_STOP_TOKENS = ("<|im_end|>", "<|endoftext|>")

__all__ = [
    "DEFAULT_HOST",
    "DEFAULT_PORT",
    "DEFAULT_STOP_TOKENS",
    "ServingProfile",
    "render_modelfile",
    "render_serve_script",
]


class ServingProfile(DomainModel):
    """Pinned serving parameters for a 4 GB GPU (Qwen3-4B, partial offload).

    Attributes:
        temperature: Sampling temperature for served answers.
        num_ctx: Context window in tokens.
        num_gpu: Transformer layers offloaded to the GPU (of Qwen3-4B's 36).
        num_parallel: Parallel request slots.
        host: Bind address of the local server.
        port: Bind port of the local server.
        stop_tokens: Stop strings for the Qwen3 chat template.
    """

    temperature: float = 0.1
    num_ctx: int = 4096
    num_gpu: int = 20
    num_parallel: int = 1
    host: str = DEFAULT_HOST
    port: int = DEFAULT_PORT
    stop_tokens: list[str] = Field(default_factory=lambda: list(DEFAULT_STOP_TOKENS))


def render_modelfile(book_title: str, profile: ServingProfile) -> str:
    """Render the Ollama Modelfile for a registered GGUF.

    The SYSTEM block embeds the shared RAG prompt contract
    (:func:`distiller.rag.prompts.build_system_prompt`), so a served model is
    prompted identically to the evaluated one.

    Args:
        book_title: Title embedded in the RAG system prompt.
        profile: Pinned serving parameters.

    Returns:
        Modelfile text: FROM, SYSTEM and PARAMETER blocks plus the commands.
    """
    stops = "\n".join(f'PARAMETER stop "{token}"' for token in profile.stop_tokens)
    return (
        "# Ollama Modelfile — generated by `distiller gguf register`.\n"
        "# Create:  ollama create <model-name> -f Modelfile\n"
        "# Run:     ollama run <model-name>\n"
        "FROM ./model.gguf\n\n"
        f'SYSTEM """{build_system_prompt(book_title)}"""\n\n'
        f"PARAMETER temperature {profile.temperature}\n"
        f"PARAMETER num_ctx {profile.num_ctx}\n"
        f"PARAMETER num_gpu {profile.num_gpu}\n"
        f"{stops}\n"
    )


def render_serve_script(model_name: str, profile: ServingProfile) -> str:
    """Render the ``serve.sh`` script for a registered GGUF.

    The script carries the exact ``llama-server`` invocation for partial GPU
    offload on a 4 GB card and the equivalent Ollama commands; it launches
    nothing by itself.

    Args:
        model_name: Served model name (Ollama name and llama-server alias).
        profile: Pinned serving parameters.

    Returns:
        Script text with the commands and the OpenAI-compatible endpoint.
    """
    llama_command = (
        f'llama-server -m "$script_dir/model.gguf" --alias {model_name} '
        f"-ngl {profile.num_gpu} -c {profile.num_ctx} -np {profile.num_parallel} "
        f"--host {profile.host} --port {profile.port}"
    )
    return (
        "#!/usr/bin/env bash\n"
        "# Serve the registered GGUF with partial GPU offload (4 GB card).\n"
        f"# OpenAI-compatible endpoint: http://localhost:{profile.port}/v1\n"
        "set -euo pipefail\n\n"
        'script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n\n'
        f"# Option A — llama.cpp ({profile.num_gpu} of Qwen3-4B's 36 layers "
        "on the GPU):\n"
        f"{llama_command}\n\n"
        "# Option B — Ollama (uses the Modelfile in this directory):\n"
        f'#   ollama create {model_name} -f "$script_dir/Modelfile"\n'
        f"#   ollama run {model_name}\n"
    )
